import type { POI } from '@/entities/poi';

// Datos reales del Parque Caldas, Popayán
// Coordenadas actualizadas y descripciones completas
export const DEMO_POIS: POI[] = [
  {
    id: 'caldas',
    name: 'Monumento a Caldas',
    description: 'Estatua dedicada al sabio Francisco José de Caldas, matemático y naturalista colombiano del siglo XVIII. Corazón geométrico del parque donde convergen los ocho senderos principales.',
    category: 'interes',
    coordinates: { lat: 2.44193, lng: -76.60631 },
    imageUrl: '/images/morro-tulcan.png',
    proximityRadiusM: 50,
    metadata: {
      horario: 'Acceso 24/7',
      entrada: 'Gratuita',
    },
  },
  {
    id: 'catedral',
    name: 'Catedral Basílica',
    description: 'Catedral Basílica Nuestra Señora de la Asunción, joya arquitectónica construida en el siglo XVI. Su fachada blanca es uno de los símbolos más reconocibles de Popayán, ubicada en el costado occidental del parque.',
    category: 'interes',
    coordinates: { lat: 2.44137, lng: -76.60655 },
    imageUrl: '/images/catedral.png',
    audioUrl: 'https://example.com/audio/catedral.mp3',
    proximityRadiusM: 50,
    metadata: {
      construida: '1558',
      estilo: 'Arquitectura colonial',
      horario: 'Lunes-Domingo 7am-6pm',
    },
  },
  {
    id: 'torre',
    name: 'Torre del Reloj',
    description: 'Torre de ladrillo rojo de casi 200 años de antigüedad, construida en 1831. Símbolo histórico de Popayán, ubicada en el costado norte del parque. Su reloj marca el tiempo del centro histórico.',
    category: 'interes',
    coordinates: { lat: 2.4414718, lng: -76.6068623 },
    imageUrl: '/images/torre-reloj.png',
    proximityRadiusM: 40,
    metadata: {
      construida: '1831',
      altura: '18 metros',
      material: 'Ladrillo',
    },
  },
  {
    id: 'ra_fachada',
    name: 'Fachada Colonial (RA)',
    description: 'Apunta tu cámara hacia la fachada de la Catedral para ver una reconstrucción histórica en 3D de cómo se veía en el siglo XVI. Experiencia de realidad aumentada interactiva.',
    category: 'ra',
    coordinates: { lat: 2.44175, lng: -76.60645 },
    imageUrl: '/images/san-francisco.png',
    arModelUrl: '/assets/models/fachada-colonial.glb',
    proximityRadiusM: 35,
    metadata: {
      tecnologia: 'WebAR',
      formato: '3D',
    },
  },
  {
    id: 'camara_principal',
    name: 'Punto de Foto Remota',
    description: 'Cámara IP de alta resolución estratégicamente ubicada para capturar la mejor vista panorámica del Parque Caldas. Solicita una foto bajo demanda que será procesada con IA para mejorar contraste y eliminar fondos.',
    category: 'camara',
    coordinates: { lat: 2.44220, lng: -76.60630 },
    imageUrl: '/images/humilladero.png',
    cameraUrl: 'http://192.168.1.50:8080',
    proximityRadiusM: 45,
    metadata: {
      resolucion: '4K',
      frecuencia: 'Tiempo real',
    },
  },
  {
    id: 'cafe',
    name: 'Café del Parque',
    description: 'Zona de descanso y cafetería con servicio de bebidas, snacks y comidas ligeras. Instalaciones disponibles incluyen baños y wifi gratuito. Ideal para pausar el recorrido y disfrutar de la atmósfera del parque.',
    category: 'serv',
    coordinates: { lat: 2.44185, lng: -76.60610 },
    imageUrl: '/images/gastronomia.png',
    proximityRadiusM: 30,
    metadata: {
      horario: '8am - 6pm',
      servicios: 'WiFi, Baños, Comida',
      telefono: '+57 1234567890',
    },
  },
  {
    id: 'humilladero',
    name: 'Puente del Humilladero',
    description: 'Emblemático puente de ladrillo construido en 1873 con doce arcos. Conecta el centro histórico con el barrio El Callejón y es uno de los íconos de Popayán.',
    category: 'interes',
    coordinates: { lat: 2.4444983, lng: -76.6050939 },
    imageUrl: '/images/humilladero.png',
    proximityRadiusM: 50,
    metadata: {
      construido: '1873',
      arcos: '12',
      material: 'Ladrillo',
    },
  },
  {
    id: 'museo',
    name: 'Museo Guillermo León Valencia',
    description: 'Casa museo dedicada a la memoria del expresidente y poeta payanés Guillermo León Valencia. Conserva mobiliario, documentos y objetos personales de la familia.',
    category: 'interes',
    coordinates: { lat: 2.4433121, lng: -76.6051461 },
    imageUrl: '/images/museo-guillermo.png',
    proximityRadiusM: 40,
    metadata: {
      tipo: 'Casa museo',
      entrada: 'Gratuita',
    },
  },
  {
    id: 'pueblito',
    name: 'Pueblito Patojo',
    description: 'Réplica a escala del Popayán colonial, ubicada al pie de El Morro de Tulcán. Recrea calles, iglesias y casas tradicionales de la Ciudad Blanca.',
    category: 'interes',
    coordinates: { lat: 2.4436, lng: -76.5993 },
    imageUrl: '/images/pueblito.png',
    proximityRadiusM: 50,
    metadata: {
      tipo: 'Réplica histórica',
      entrada: 'Gratuita',
    },
  },
  {
    id: 'morro',
    name: 'El Morro de Tulcán',
    description: 'Pirámide precolombina coronada por la estatua ecuestre de Sebastián de Belalcázar. Mirador natural con la mejor vista panorámica de Popayán y su centro histórico.',
    category: 'interes',
    coordinates: { lat: 2.4447582, lng: -76.6001125 },
    imageUrl: '/images/morro.png',
    proximityRadiusM: 60,
    metadata: {
      tipo: 'Sitio arqueológico / Mirador',
      entrada: 'Gratuita',
    },
  },
  {
    id: 'teatro',
    name: 'Teatro Municipal Guillermo Valencia',
    description: 'Principal escenario cultural de Popayán, inaugurado en 1927. Sede de obras de teatro, conciertos y eventos del Festival de Música Religiosa.',
    category: 'interes',
    coordinates: { lat: 2.4430221, lng: -76.606178 },
    imageUrl: '/images/teatro.png',
    proximityRadiusM: 40,
    metadata: {
      inaugurado: '1927',
      tipo: 'Teatro',
    },
  },
  {
    id: 'santodomingo',
    name: 'Iglesia de Santo Domingo',
    description: 'Templo barroco del siglo XVIII, una de las joyas arquitectónicas del centro histórico. Destaca su portada tallada en piedra y su retablo dorado.',
    category: 'interes',
    coordinates: { lat: 2.4416557, lng: -76.6045709 },
    imageUrl: '/images/santo%20domingo.png',
    proximityRadiusM: 40,
    metadata: {
      estilo: 'Barroco',
      siglo: 'XVIII',
    },
  },
  {
    id: 'alcaldia',
    name: 'Alcaldía Municipal',
    description: 'Sede del gobierno municipal de Popayán, ubicada en el corazón del centro histórico junto al Parque Caldas.',
    category: 'interes',
    coordinates: { lat: 2.4418025, lng: -76.6053897 },
    imageUrl: '/images/alcaldia.png',
    proximityRadiusM: 40,
    metadata: {
      tipo: 'Edificio público',
    },
  },
  {
    id: 'ermita',
    name: 'Iglesia La Ermita',
    description: 'El templo más antiguo de Popayán, construido en el siglo XVI. Pequeña capilla de gran valor histórico y religioso para la Ciudad Blanca.',
    category: 'interes',
    coordinates: { lat: 2.440168, lng: -76.6026448 },
    imageUrl: '/images/ermita.png',
    proximityRadiusM: 40,
    metadata: {
      siglo: 'XVI',
      tipo: 'Templo',
    },
  },
  {
    id: 'lovepopayan',
    name: 'Letrero Popayán',
    description: 'Letrero turístico de Popayán, punto fotográfico popular junto al Río Molino y el Puente del Humilladero.',
    category: 'interes',
    coordinates: { lat: 2.44453, lng: -76.60565 },
    imageUrl: '/images/lovepopayan.png',
    proximityRadiusM: 30,
    metadata: {
      tipo: 'Punto fotográfico',
    },
  },

  // --- Restaurantes (OSM, sin foto: se muestran con ícono) ---
  {
    id: 'rest-laradio',
    name: 'La Radio - Rock y Food',
    description: 'Restaurante y bar con ambiente rockero en el centro de Popayán.',
    category: 'restaurante',
    coordinates: { lat: 2.44424, lng: -76.6072692 },
  },
  {
    id: 'rest-tequilas',
    name: "Tequila's",
    description: 'Restaurante de comida mexicana en el centro histórico.',
    category: 'restaurante',
    coordinates: { lat: 2.4421877, lng: -76.6088803 },
  },
  {
    id: 'rest-italiano',
    name: 'Restaurante Italiano',
    description: 'Cocina italiana, pastas y pizzas en el centro de Popayán.',
    category: 'restaurante',
    coordinates: { lat: 2.4429146, lng: -76.6080827 },
  },
  {
    id: 'rest-pizzarra',
    name: 'Pizzarra',
    description: 'Pizzería popular del centro histórico.',
    category: 'restaurante',
    coordinates: { lat: 2.441775, lng: -76.6079056 },
  },
  {
    id: 'rest-mana',
    name: 'Restaurante Vegetariano Maná',
    description: 'Comida vegetariana y saludable cerca del centro.',
    category: 'restaurante',
    coordinates: { lat: 2.440842, lng: -76.6097337 },
  },
  {
    id: 'rest-taller',
    name: 'Taller de Cocina',
    description: 'Propuesta gastronómica de autor en Popayán.',
    category: 'restaurante',
    coordinates: { lat: 2.4435415, lng: -76.6082719 },
  },

  // --- Hoteles (OSM, sin foto: se muestran con ícono) ---
  {
    id: 'hotel-dann',
    name: 'Hotel Dann Monasterio',
    description: 'Hotel histórico ubicado en un antiguo monasterio del centro de Popayán.',
    category: 'hotel',
    coordinates: { lat: 2.4435825, lng: -76.6092283 },
  },
  {
    id: 'hotel-real',
    name: 'Hotel Real',
    description: 'Hotel en pleno centro histórico de Popayán.',
    category: 'hotel',
    coordinates: { lat: 2.4452439, lng: -76.6047047 },
  },
  {
    id: 'hotel-royal',
    name: 'Hotel Royal',
    description: 'Alojamiento cercano al centro de la Ciudad Blanca.',
    category: 'hotel',
    coordinates: { lat: 2.4460063, lng: -76.6048299 },
  },
  {
    id: 'hotel-granposada',
    name: 'La Gran Posada',
    description: 'Hotel tradicional en el centro de Popayán.',
    category: 'hotel',
    coordinates: { lat: 2.4465272, lng: -76.6041503 },
  },
  {
    id: 'hotel-gaitana',
    name: 'Hotel La Gaitana',
    description: 'Alojamiento en el centro histórico de Popayán.',
    category: 'hotel',
    coordinates: { lat: 2.4465175, lng: -76.6077592 },
  },
  {
    id: 'hotel-krone',
    name: 'Hotel Krone',
    description: 'Hotel boutique de estilo europeo en Popayán.',
    category: 'hotel',
    coordinates: { lat: 2.4403203, lng: -76.6081565 },
  },

  // --- Supermercados (OSM, sin foto: se muestran con ícono) ---
  {
    id: 'super-provitec',
    name: 'Supermercado Provitec',
    description: 'Supermercado en el centro de Popayán.',
    category: 'supermercado',
    coordinates: { lat: 2.440394, lng: -76.6074272 },
  },
  {
    id: 'super-olimpica',
    name: 'Olímpica',
    description: 'Cadena de supermercados, sede cercana al centro.',
    category: 'supermercado',
    coordinates: { lat: 2.4469375, lng: -76.6057923 },
  },
  {
    id: 'super-d1',
    name: 'D1',
    description: 'Tienda de descuento D1 en el centro de Popayán.',
    category: 'supermercado',
    coordinates: { lat: 2.4384414, lng: -76.6050223 },
  },
  {
    id: 'super-solarte',
    name: 'Supertienda Solarte',
    description: 'Supertienda de barrio cerca del centro histórico.',
    category: 'supermercado',
    coordinates: { lat: 2.4382697, lng: -76.6058927 },
  },
  {
    id: 'super-remesa',
    name: 'La Remesa Market',
    description: 'Mercado y supermercado cercano al centro.',
    category: 'supermercado',
    coordinates: { lat: 2.4431969, lng: -76.6132842 },
  },
  {
    id: 'super-merkatrueke',
    name: 'Merka Trueke',
    description: 'Supermercado en el centro de Popayán.',
    category: 'supermercado',
    coordinates: { lat: 2.4383856, lng: -76.6078916 },
  },
];